// Button Configuration for Multipass Terminal
// This file controls the quick command buttons that appear below the terminal
// This file is auto-generated by the UI settings. Edit with caution.

module.exports = {
  "ai": {
    "start": {
      "label": "AI Assistant",
      "mobileLabel": "🤖 AI",
      "className": "bg-blue-600",
      "title": "Start AI Assistant",
      "command": "claude"
    },
    "exit": {
      "label": "Exit AI",
      "mobileLabel": "🛑 Exit",
      "exitSequence": null,
      "className": "bg-red-600",
      "title": "Exit AI Assistant"
    }
  },
  "quickCommands": [
    {
      "label": "ls -la",
      "command": "ls -la\n",
      "className": "bg-gray-600",
      "title": "List files with details"
    },
    {
      "label": "pwd",
      "command": "pwd\n",
      "className": "bg-gray-600",
      "title": "Print working directory"
    },
    {
      "label": "git status",
      "command": "git status\n",
      "className": "bg-gray-600",
      "title": "Show git status"
    },
    {
      "label": "git log",
      "command": "git log --oneline -10\n",
      "className": "bg-gray-600",
      "title": "Show recent git commits"
    },
    {
      "label": "npm run",
      "command": "npm run\n",
      "className": "bg-gray-600",
      "title": "List npm scripts"
    },
    {
      "label": "clear",
      "command": "clear\n",
      "className": "bg-gray-600",
      "title": "Clear terminal screen"
    }
  ],
  "utilityButtons": {
    "copy": {
      "label": "📋 Copy",
      "className": "bg-green-600",
      "title": "Copy selected text (Ctrl+C)"
    },
    "paste": {
      "label": "📝 Paste",
      "className": "bg-green-600",
      "title": "Paste from clipboard (Ctrl+V)"
    },
    "shiftTab": {
      "label": "⇧ Tab",
      "command": "\u001b[Z",
      "className": "bg-purple-600",
      "title": "Send Shift+Tab"
    },
    "pulseTab": {
      "label": "Pulse Tab",
      "command": "\u001b[Z",
      "className": "bg-gray-600",
      "title": "Send Shift+Tab to all terminals",
      "broadcast": true
    },
    "escape": {
      "label": "Esc",
      "command": "\u001b",
      "className": "bg-yellow-600",
      "title": "Send Escape key"
    }
  },
  "mobile": {
    "showHelpText": true,
    "helpText": "Tip: Long press command buttons to copy"
  }
};