const path = require('path');

class AIReadmeGenerator {
    static generateContent(cubicleIndex, projectDir, options = {}) {
        const {
            repoUrl = null,
            sessionName = `ai-office-cubicle-${cubicleIndex}`,
            description = `AI Office workspace in ${projectDir}`
        } = options;

        const timestamp = new Date().toISOString();
        
        let content = `# AI Office - Cubicle ${cubicleIndex}

Generated: ${timestamp}
Session: ${sessionName}
Working Directory: ${projectDir}

## Description
${description}

## Quick Commands
- Start session: \`tmux attach -t ${sessionName}\`
- List files: \`ls -la\`
- Git status: \`git status\`
- Run AI assistant: \`claude\` or configured LLM command
`;

        if (repoUrl) {
            content += `
## Repository
Remote: ${repoUrl}
`;
        }

        content += `
## Notes
This file is automatically generated for AI context.
Add your project-specific notes below this line.
---
`;

        return content;
    }

    static generateMinimalContent(sessionName, workingDir) {
        return `Session: ${sessionName}
Directory: ${workingDir}
Generated: ${new Date().toISOString()}
`;
    }
}

module.exports = AIReadmeGenerator;